Not Found: /favicon.ico
Not Found: /favicon.ico
Unauthorized: /logout/
Not Found: /favicon.ico
Unauthorized: /api/documents/
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for field_name in existing + allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
TypeError: unsupported operand type(s) for +: 'set' and 'set'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
NameError: name 'field_name' is not defined
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
NameError: name 'field_name' is not defined
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for existing in field_name - allowed:
NameError: name 'field_name' is not defined
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for field_name in existing - field_name:
UnboundLocalError: local variable 'field_name' referenced before assignment
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for field_name in existing - field_name:
UnboundLocalError: local variable 'field_name' referenced before assignment
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 16, in __init__
    for field_name in existing - field_name:
UnboundLocalError: local variable 'field_name' referenced before assignment
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 10, in __init__
    fields = self.context['request'].query_params.exclude('fields')
AttributeError: 'QueryDict' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 17, in __init__
    self.fields.exclude(field_name)
AttributeError: 'BindingDict' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 17, in __init__
    self.fields.exclude(field_name)
AttributeError: 'BindingDict' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 17, in __init__
    self.fields.exclude(field_name)
AttributeError: 'BindingDict' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 15, in __init__
    existing = set(self.exclude.keys())
AttributeError: 'SafetyEquipmentSerializer' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 1117, in get_field_names
    assert not (fields and exclude), (
AssertionError: Cannot set both 'fields' and 'exclude' options on serializer SafetyEquipmentSerializer.
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 1112, in get_field_names
    raise TypeError(
TypeError: The `exclude` option must be a list or tuple. Got str.
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 15, in __init__
    existing = set(self.exclude.keys())
AttributeError: 'SafetyEquipmentSerializer' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 15, in __init__
    existing = set(self.exclude.keys())
AttributeError: 'SafetyEquipmentSerializer' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 15, in __init__
    existing = set(self.fields.keys())
AttributeError: 'SafetyEquipmentSerializer' object has no attribute 'exclude'
Internal Server Error: /api/safetyequipment/
Traceback (most recent call last):
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/oghabas1/virtualenv/backend/3.10/lib/python3.10/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/home/oghabas1/backend/property/serializer.py", line 15, in __init__
    existing = set(self.fields.keys())
AttributeError: 'SafetyEquipmentSerializer' object has no attribute 'exclude'
Unauthorized: /api/safetyequipment/
Not Found: /favicon.ico
Not Found: /favicon.ico
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Unauthorized: /token/
Unauthorized: /token/
Unauthorized: /token/
Bad Request: /token/refresh/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /token/
Bad Request: /token/refresh/
Unauthorized: /logout/
Not Found: /favicon.ico
